### ISSUE TITLE
Add .editorconfig

### ISSUE THREAD

**Issue by Ahacad** [CLDXiang/node-typescript-eslint-airbnb-prettier-template#1]
Ref: https://editorconfig.org/

Enforce styles across operating systems and editors.

**Comment by CLDXiang** [comment]
Is this still necessary when we already had eslint + prettier?  🤔

**Comment by Ahacad** [comment]
I think [this article](https://blog.theodo.com/2019/08/why-you-should-use-eslint-prettier-and-editorconfig-together/) is a good read, and this [stackoverflow answer](https://stackoverflow.com/questions/48363647/editorconfig-vs-eslint-vs-prettier-is-it-worthwhile-to-use-them-all) also explains the relationships between the three.

To summarize:
- Eslint: code quality + formatting
- Prettier: only formatting but much better than Eslint
- editorconfig: enforce formatting *while you are writing code*, prettier formats your code after saving
